apiVersion: apps/v1
kind: Deployment
metadata:
  name: vijai
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-test
  template:
    metadata:
      labels:
        app: myapp-test
    spec:
      containers:
      - name: myapp
        image: busybox