@Library('jenkins-shared-library') _

pipeline {
   agent {
      label "docker-slave"
   }
    stages {
        stage('Terraform Execution Init') {
            steps {
                executeTerraform("${params.PROJECT_PATH}","${params.ACTION}")
            }
        }
    }
}