@Library('jenkins-shared-library@master') _

pipeline {
   agent any
    stages {
        stage('Terraform Execution') {
            steps {
                script {
                    projectPath ='terraform/learning-basics/local/local-file-creation'
                    executeTerraform(projectPath,"${params.ACTION}")
                }
            }
        }
    }
}