@Library('jenkins-shared-library@master') _

pipeline {
   agent any
    stages {
        stage('Terraform Execution') {
            steps {
                projectPath ='terraform/learning-basics/local/first-tf-code'
                executeTerraform(projectPath,"${params.ACTION}")
            }
        }
    }
}