@Library('jenkins-shared-library@master') _

pipeline {
   agent any
    stages {
        stage('Gradle Build Execute') {
            steps {
                script {
                    appPath = 'sample-applications-builders/gradle/credit-card-management'
                    buildGradle(appPath)
                }
                
            }
        }
    }
}
