apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      slack:
        token: xoxb-1894845351649-1888399356868-zS6ThuK1YwuazPyu8bXKmRpI
        channel: k8s-notification
         
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
      secret: false
      configmap: false