version: '3.9'
services:
  api:
    build: 
      context: .
    ports:
      - "8080:8086"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=kavitha
      - SPRING_DATASOURCE_PASSWORD=kavitha
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=kavitha
      - POSTGRES_USER=kavitha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kavitha"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: {}