pipeline{
  agent { 
    label "docker-slave"
  }
  stages {
    stage('Build maven ') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
      post {
        success {
          archiveArtifacts(artifacts: 'target/*.jar', fingerprint: true)
        }
      }
    }
  }
}