@Library('jenkins-shared-library@master') _

pipeline {
    agent any
    stages {
        stage('Maven Builder Init') {
            steps {
                script {
                   buildMaven()
                }
            }
        }
    }
}