version: '3'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - 9393:9300
    volumes:
      - /Users/vijai/Personal/Learning/Playgrounds/infocloud-assessment/solutions/inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'